// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prnkonohgbvmufyvdpoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybmtvbm9oZ2J2bXVmeXZkcG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MDc0ODcsImV4cCI6MjA1MDM4MzQ4N30.Z1hsLD-1bbedwcAiWrzst6L8AZrtCustDpNfVbTDc4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);